feat: первая итерация
GSBoldyrev/java-shareit pull request #1
Opened 2022-10-20 19:15 UTC by GSBoldyrev

2022-10-21 19:12 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-10-21 19:12 UTC, FanaticFiz commented on pom.xml
>  		<pluginManagement>
Корректно представься гиту...
https://pastenow.ru/JB70B

2022-10-21 19:12 UTC, FanaticFiz commented on pom.xml
> +            <plugin>
1. Хорошей практикой будет указать кодировку
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2. Я советую всем соблюдать некий порядок при объявлении зависимостей.
Сначала "главный" `spring` все его зависимости и всё о нём.
Потом по степени "тяжеловестности" остальные зависимости. Ну и у меня в проекте, например, последними идёт еще одна секция наши собственные библиотеки/модули/контракты.

3. Объявил версию java используй!
```
                    <source>11</source>
                    <target>11</target>
```

2022-10-21 19:12 UTC, FanaticFiz commented on pom.xml
> +            </plugin>
Про файл настроек, так как он не менялся, тут напишу...
Мы же в предыдущем проекте уже про это говорили!?
Почему настройки снова как `application.properties` ?

Я буду топить за то чтобы ты сразу привыкал к написанию файла свойств для приложения в формате `yaml -> application.yml`
Мне трудно сейчас представить проект в котором до сих пор на него не пересели ))

Соответственно - попрошу тебя этому следовать...

Мы каждый проект будем с этого начинать?
Расстраиваешь ты меня! )))

2022-10-21 19:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/error/model/ErrorResponse.java
> +public class ErrorResponse {
С ексепшенами всё хорошо...

2022-10-21 19:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +
Тут что то было.... вангую что какой нить лог ))

2022-10-21 19:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        List<ItemDto> result = new ArrayList<>();
Хочешь сказать что наставник рекомендовал вам не прокидывать dto в сервис?

2022-10-21 19:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        for (Item i: items) {
Напиши это же 

```
        List<Item> items = service.getAll(userId);
        List<ItemDto> result = new ArrayList<>();
        for (Item i: items) {
            result.add(toItemDto(i));
        }

        return result;
```

в функциональном стиле... 

```
    @GetMapping
    public List<ItemDto> getItems(@RequestHeader("X-Sharer-User-Id") long userId) {
        return service.getAll(userId)
                          ........................
                          ........................
    }
```

2022-10-21 19:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                           @RequestBody ItemDto itemDto) {
Нет валидации?

2022-10-21 19:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Long id;
Валидация должна быть у DTO моделей, а не у `Item` !

2022-10-21 19:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private void checkOwner(long userId) {
Если твой метод делает throw, то лучше его так и назвать...
`throwIfNotExist`

Но вообще лучше чтобы get метод возвращал `Optional` тогда можно будет этим воспользоваться...

2022-10-21 19:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +        return items.get(itemId);
Когда метод начинается сразу с return то пустая строка не нужна...

2022-10-21 19:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    Item get(long itemId);
Вообще в репозитории лучше использовать глагол `find`, а в сервисах `get`.
Про Optional я уже писал: `Optional<Item> get(long itemId);`

2022-10-21 19:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +    public static User toUser(UserDto userDto) {
Почему только в одну сторону?

2022-10-21 19:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +public interface UserRepository {
Опять же, посмотри на схожие интерфейсы, может сделаем с этим что-то?

2022-10-22 17:11 UTC, GSBoldyrev commented on pom.xml
>  		<pluginManagement>
Сделано! Хотя, надо было еще на первых спринтах это сделать ))

2022-10-22 18:01 UTC, GSBoldyrev commented on pom.xml
> +            </plugin>
Переделал!))

2022-10-22 21:35 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private void checkOwner(long userId) {
Сделано!

2022-10-22 21:36 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +    public static User toUser(UserDto userDto) {
Сделано!

2022-10-22 21:36 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    Item get(long itemId);
Сделано!

2022-10-22 21:47 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        for (Item i: items) {
сделано!

2022-10-22 21:47 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                           @RequestBody ItemDto itemDto) {
Валидацию поправил...

2022-10-22 21:47 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Long id;
ага...

2022-10-22 21:48 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +        return items.get(itemId);
исправил

2022-10-22 21:48 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +public interface UserRepository {
сделано!

2022-10-24 18:37 UTC, FanaticFiz approved these changes

2022-10-24 18:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    }
Выровнять и идеально ))

```
    public List<ItemDto> getAll(long userId) {
        return repository.findAll().stream()
                         .filter(item -> item.getOwnerId() == userId)
                         .map(ItemMapper::toItemDto)
                         .collect(Collectors.toList());
    }
```

2022-10-24 18:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    private void checkEmail(User user) {
Если мы в методе throw что то, то и назвать метод надо throwIf и причина...

2022-11-05 17:02 UTC, merged