Add bookings
GSBoldyrev/java-shareit pull request #2
Opened 2022-11-10 19:37 UTC by GSBoldyrev

2022-11-11 19:33 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-11 19:33 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            throw new NotFoundException("Собрались бронировать собственную вещь?");
Ну здесь то уместнее `ConflictException` или `BadRequestException`

2022-11-11 19:33 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        booking.setStatus(Status.WAITING);
Помнишь же что можно импорить статики: `booking.setStatus(WAITING);`

2022-11-11 19:33 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "end_time")
Не хватает указания что поле не может быть `null`, как в БД не хватает этого так и тут.
Для этого есть спец. возможность в `Column`

Пройдись по всем полям, добейся согласованности с БД.

2022-11-11 19:33 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS bookings
Тут тоже можно и нужно выравнивать код.

```
CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE,
    end_time   TIMESTAMP WITHOUT TIME ZONE,
    item_id    BIGINT REFERENCES items (id) ON DELETE CASCADE,
    booker_id  BIGINT REFERENCES users (id) ON DELETE CASCADE,
    status     VARCHAR(40)                             NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);
```

2022-11-11 19:33 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    start_time TIMESTAMP WITHOUT TIME ZONE,
Даты `NOT NULL`

2022-11-11 19:33 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(value = "select * from bookings where item_id in (select id from items where owner_id = ?1) order by id desc", nativeQuery = true)
Оформляй запросы. 
Пиши команды SQL в верхнем регистре: `SELECT * FROM bookings`

2022-11-11 19:33 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(value = "select * from bookings where item_id in (select id from items where owner_id = ?1) order by id desc", nativeQuery = true)
Если строка не влазит в 120 символов, то надо делать перенос

2022-11-11 19:33 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +}
Подозрительно мало у тебя методов в этом репозитории.
В остальных работах тут прям не менее 10, на все случаи жизни как сказать...

2022-11-11 19:33 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +                        .filter(b -> b.getEnd().isAfter(LocalDateTime.now()))
Вот причина того что у тебя мало методов в репозитории!

Ты делаешь неверно! Ты выгребаешь всё: `findAllByOwner` а потом начинаешь это фильтровать!

А БД тогда зачем существует? 
Надо, правильным запросом, выгрести именно то что тебе нужно.

Ты же должен понимать что ты не сможешь выбрать все записи когда их будет оооочень много!

2022-11-11 19:33 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        return repository.findAllByOwnerId(userId).stream()
Видишь, в этом сервисе у тебя много репозиториев и уже не хорошо именовать как `repository`, уже надо конкретизировать.

2022-11-12 08:38 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(value = "select * from bookings where item_id in (select id from items where owner_id = ?1) order by id desc", nativeQuery = true)
готово!

2022-11-12 08:41 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            throw new NotFoundException("Собрались бронировать собственную вещь?");
У меня там сначала и стоял Конфликт, но тесты постмана требуют код 404, который у меня, да и вообще по логике дает NotFound..

2022-11-12 08:44 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        booking.setStatus(Status.WAITING);
Вспомнил!

2022-11-12 12:10 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "end_time")
Исправил!

2022-11-12 12:10 UTC, GSBoldyrev commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS bookings
Сделано!

2022-11-12 12:11 UTC, GSBoldyrev commented on src/main/resources/schema.sql
> +    start_time TIMESTAMP WITHOUT TIME ZONE,
Сделано!

2022-11-12 12:12 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        return repository.findAllByOwnerId(userId).stream()
Сделано!

2022-11-13 19:11 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +}
ага...

2022-11-13 19:11 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +                        .filter(b -> b.getEnd().isAfter(LocalDateTime.now()))
Да, понял ошибку, потрудился, исправил...

2022-11-14 01:46 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            throw new NotFoundException("Собрались бронировать собственную вещь?");
Да есть такое, другие ребята тоже отписывались об этом. Следуем спецификации.

2022-11-14 01:49 UTC, FanaticFiz approved these changes

2022-11-21 06:40 UTC, merged