fix: 16й спринт, первая итерация
GSBoldyrev/java-shareit pull request #3
Opened 2022-11-28 07:54 UTC by GSBoldyrev

2022-11-29 04:03 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-29 04:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public ItemRequestDto addRequest(@RequestHeader("X-Sharer-User-Id") long userId,
У тебя в приложении как то совсем не используется логгер...
Было бы полезно логировать входные параметры/модели в контроллерах, например.
Где нить на уровне `debug`

2022-11-29 04:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +            throw new NotFoundException("Пользователь не найден");
Давай больше информации в логи и в сообщения клиенту... не найдено по какому параметру/значению?

2022-11-29 04:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +        Pageable page = PageRequest.of(from / size, size, Sort.by("created").ascending());
Почему тут не проверили существование пользователя?

2022-11-29 04:03 UTC, FanaticFiz commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        when(service.getForOwner(anyLong(), anyString(), anyInt(), anyInt()))
Образцовые тесты, всё чётенько, каждый тест разбит на три шага...

Статики только можно заимпортить

```
                        .characterEncoding(UTF_8)
                        .contentType(APPLICATION_JSON)
                        .accept(APPLICATION_JSON)
```

2022-11-30 19:54 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public ItemRequestDto addRequest(@RequestHeader("X-Sharer-User-Id") long userId,
сделано!

2022-11-30 19:59 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +            throw new NotFoundException("Пользователь не найден");
сделано!

2022-11-30 20:00 UTC, GSBoldyrev commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +        Pageable page = PageRequest.of(from / size, size, Sort.by("created").ascending());
сделано!

2022-11-30 20:03 UTC, GSBoldyrev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        when(service.getForOwner(anyLong(), anyString(), anyInt(), anyInt()))
все!

2022-12-01 18:37 UTC, FanaticFiz approved these changes

2022-12-01 18:40 UTC, merged